// app/questions/page.tsx
"use client"; // Add this line at the top

import { useEffect, useState } from "react";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";

interface QuestionItem {
  question: string;
  answer: string;
}

interface QuestionCategory {
  category: string;
  items: QuestionItem[];
}

export default function QuestionsPage() {
  const [questions, setQuestions] = useState<QuestionCategory[]>([]);
  const [activeCategory, setActiveCategory] = useState<string | null>(null);
  const [isMounted, setIsMounted] = useState(false); // New state to track if component is mounted

  useEffect(() => {
    const fetchQuestions = async () => {
      const res = await fetch(`/data/questionsv2.json`);
      const data = await res.json();
      setQuestions(data.questions);
      setIsMounted(true); // Set mounted state to true after fetching
    };

    fetchQuestions();
  }, []);

  // Function to scroll to the section based on the hash
  const scrollToHash = (hash: string) => {
    const element = document.getElementById(hash);
    if (element) {
      const headerOffset = 100; // Adjust this if you have a fixed header
      const elementPosition = element.getBoundingClientRect().top;
      const offsetPosition = elementPosition + window.pageYOffset - headerOffset;
      window.scrollTo({
        top: offsetPosition,
        behavior: "smooth",
      });
    }
  };

  // Handle initial hash and scroll after questions are fetched
  useEffect(() => {
    if (isMounted) { // Check if component has mounted
      const hash = window.location.hash.replace("#", "");
      if (hash) {
        setActiveCategory(hash);
        scrollToHash(hash);
      }
    }
  }, [isMounted]); // Run when isMounted changes

  // Handle hash changes
  useEffect(() => {
    const handleHashChange = () => {
      const hash = window.location.hash.replace("#", "");
      if (hash) {
        setActiveCategory(hash);
        scrollToHash(hash);
      }
    };

    window.addEventListener("hashchange", handleHashChange);
    return () => {
      window.removeEventListener("hashchange", handleHashChange);
    };
  }, []);

  return (
    <main className="container mx-auto px-4 py-8">
      <h1 className="text-4xl font-bold tracking-tight mb-8">Frequently Asked Questions</h1>

      <div className="space-y-8">
        {questions.map((category) => (
          <div key={category.category}>
            <h2
              className={`text-2xl font-semibold mb-4 ${activeCategory === category.category.toLowerCase() ? 'text-blue-500' : ''}`}
              id={category.category.toLowerCase()}
            >
              {category.category} Questions
            </h2>
            <Accordion type="single" collapsible className="w-full">
              {category.items.map((item, index) => (
                <AccordionItem key={index} value={`${category.category}-${index}`}>
                  <AccordionTrigger className="text-left">{item.question}</AccordionTrigger>
                  <AccordionContent>
                    <p className="text-muted-foreground">{item.answer}</p>
                  </AccordionContent>
                </AccordionItem>
              ))}
            </Accordion>
          </div>
        ))}
      </div>
    </main>
  );
}

// src/app/pages/questions/questions.component.ts
import { Component, OnInit, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute } from '@angular/router';
import { QuestionsService } from '../../services/questions.service';
import { QuestionCategory } from '../../models/questions.model';

@Component({
  selector: 'app-questions',
  imports: [CommonModule],
  templateUrl: './questions.component.html',
})
export class QuestionsComponent implements OnInit {
  private questionsService = inject(QuestionsService);
  private route = inject(ActivatedRoute);

  questions = signal<QuestionCategory[]>([]);
  activeCategory = signal<string | null>(null);
  openItems = signal<Set<string>>(new Set());

  ngOnInit() {
    this.questionsService.getQuestions().subscribe(data => {
      this.questions.set(data);
      // Handle initial fragment after data loads
      this.route.fragment.subscribe(fragment => {
        if (fragment) {
          this.activeCategory.set(fragment);
          setTimeout(() => this.scrollToSection(fragment), 100);
        }
      });
    });
  }

  scrollToSection(id: string) {
    const el = document.getElementById(id);
    if (el) {
      const offset = 100;
      const pos = el.getBoundingClientRect().top + window.pageYOffset - offset;
      window.scrollTo({ top: pos, behavior: 'smooth' });
    }
  }

  toggleItem(key: string) {
    this.openItems.update(set => {
      const next = new Set(set);
      if (next.has(key)) {
        next.delete(key);
      } else {
        next.add(key);
      }
      return next;
    });
  }

  isOpen(key: string): boolean {
    return this.openItems().has(key);
  }
}

<main class="container mx-auto px-4 py-8">
  <h1 class="text-4xl font-bold tracking-tight mb-8">Frequently Asked Questions</h1>

  <div class="space-y-8">
    @for (category of questions(); track category.category) {
      <div>
        <h2
          [id]="category.category.toLowerCase()"
          class="text-2xl font-semibold mb-4 transition-colors"
          [class.text-blue-500]="activeCategory() === category.category.toLowerCase()"
        >
          {{ category.category }} Questions
        </h2>

        <div class="w-full border rounded-md divide-y divide-border">
          @for (item of category.items; track item.question; let i = $index) {
            <div class="px-4">
              <button
                class="flex w-full items-center justify-between py-4 text-left text-sm font-medium transition-all hover:underline"
                (click)="toggleItem(category.category + '-' + i)"
              >
                <span>{{ item.question }}</span>
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  class="h-4 w-4 shrink-0 ml-2 transition-transform duration-200"
                  [class.rotate-180]="isOpen(category.category + '-' + i)"
                  fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"
                >
                  <polyline points="6 9 12 15 18 9"></polyline>
                </svg>
              </button>
              @if (isOpen(category.category + '-' + i)) {
                <div class="pb-4 pt-0 text-sm text-muted-foreground">
                  {{ item.answer }}
                </div>
              }
            </div>
          }
        </div>
      </div>
    }
  </div>
</main>
